### ISSUE TITLE
Build as a library

### ISSUE THREAD

**Issue by Shadow53** [rudolfschmidt/acc#2]
I would love to see this written as a library that can be used in other projects. I've been using a custom script using `dialog` with `ledger` for a TUI experience, and a library would enable me to use the core code with a TUI.

**Comment by rudolfschmidt** [comment]
Can you explain to me more what you mean with "library"? 

When I make acc to be a library in a sense of how rust works it just makes sense for devs to include functions from acc in other rust projects but I guess you do not mean that if I am not wrong?

I guess you need more features to print information in the way that can be reused and parsed by your script. The term script I guess means not rust code?

If you tell me which features you need exactly I can consider them to be implemented.

Thanks for your contribution!

**Comment by Shadow53** [comment]
I mean making most/all of the core functionality available through `lib.rs` for use by other Rust programs. I would want to write a program that uses the library to parse the ledger file(s) and display/interact with it using a TUI, perhaps using the `cursive` crate. I am currently doing a similar thing with `ledger` and `dialog` in a shell script, but --- if I were to use acc --- it would make things easier to be able to write a proper program instead.

I hope that makes more sense?

**Comment by rudolfschmidt** [comment]
> I mean making most/all of the core functionality available through `lib.rs` for use by other Rust programs. I would want to write a program that uses the library to parse the ledger file(s) and display/interact with it using a TUI, perhaps using the `cursive` crate. I am currently doing a similar thing with `ledger` and `dialog` in a shell script, but --- if I were to use acc --- it would make things easier to be able to write a proper program instead.
> 
> I hope that makes more sense?

absolutely, it's a great idea, I had also similar thoughts to provide ncurses features to acc in the future. especially it's great to collapse and uncollapse accounts for more details or to look to the reserve side of an account that GnuCash provides for example.

I will make acc available as a lib when binary and lib at the same time are supported.

Thanks for the suggestion!

You are welcome to help to add ncurses functionalities to acc.

**Comment by Shadow53** [comment]
> I will make acc available as a lib when binary and lib at the same time are supported.

That's [already supported](https://stackoverflow.com/questions/26946646/rust-package-with-both-a-library-and-a-binary) by Rust.

> You are welcome to help to add ncurses functionalities to acc.

I may, in the future, once acc has the features I need (or I help add them) and I'm caught up on a couple of my own projects.

**Comment by rudolfschmidt** [comment]
Im going to provide acc as a lib and thinking which functions I should provide for the lib. You said you need the parser, just the raw parser or also the logic behind, models, different checkups? I guess so, right?

**Comment by rudolfschmidt** [comment]
I published v0.1.2 as lib and bin. Can you please check it? Had not time to test it before

Edit:
I fixed some issues with the lib and tested the lib. Its available. Please open a new issue if the lib does not work. You are more welcome to contribute to the TUI if you like. 

Maybe I can open a team repo with name acc and open a sub repo for you? 

Which features do you miss in acc?

**Comment by Shadow53** [comment]
I am not sure. I am focusing on a couple of my own projects right now since they need to be done ASAP. As I give myself more time, I intend to try command-line acc and go from there.

**Comment by rudolfschmidt** [comment]
You are welcome!
